import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto'
import { WebSocketServer } from 'ws'
import { getProvider, listProviders, registerProvider } from './gateway/provider-registry.mjs'
import { claudeCliProvider } from './gateway/providers/claude-cli.mjs'

registerProvider(claudeCliProvider)

const PORT = Number(process.env.GATEWAY_WS_PORT ?? process.env.WS_PORT ?? 8788)
const HOST = process.env.GATEWAY_WS_HOST ?? process.env.WS_HOST ?? '127.0.0.1'
const TOKEN = process.env.GATEWAY_TOKEN ?? process.env.CLAUDE_BRIDGE_TOKEN ?? randomBytes(24).toString('hex')
const TOKEN_AUTOGENERATED = !process.env.GATEWAY_TOKEN && !process.env.CLAUDE_BRIDGE_TOKEN
const MAX_CLIENTS = Number(process.env.GATEWAY_MAX_CLIENTS ?? process.env.CLAUDE_MAX_CLIENTS ?? 4)
const MAX_PROMPT_LENGTH = Number(process.env.GATEWAY_MAX_PROMPT_LEN ?? process.env.CLAUDE_MAX_PROMPT_LEN ?? 20_000)
const MAX_SYSTEM_PROMPT_LENGTH = Number(process.env.GATEWAY_MAX_SYSTEM_PROMPT_LEN ?? 12_000)
const MAX_OUTPUT_BYTES = Number(process.env.GATEWAY_MAX_OUTPUT_BYTES ?? 2_000_000)
const DEFAULT_ORIGINS = [
  'http://localhost:5199',
  'http://127.0.0.1:5199',
  'http://localhost:5173',
  'http://127.0.0.1:5173',
]
const ALLOWED_ORIGINS = new Set(
  process.env.ALLOWED_ORIGINS?.split(',').map((value) => value.trim()).filter(Boolean) ?? DEFAULT_ORIGINS,
)
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const SAFE_ID_PATTERN = /^[a-z0-9][a-z0-9._-]{0,99}$/i
const TOOL_POLICIES = new Set(['none', 'read-only', 'standard'])

function safeEqual(left, right) {
  const a = Buffer.from(String(left))
  const b = Buffer.from(String(right))
  return a.length === b.length && timingSafeEqual(a, b)
}

function verifyClient({ origin, req }, done) {
  if (origin && !ALLOWED_ORIGINS.has(origin)) {
    done(false, 403, 'Origin tidak diizinkan')
    return
  }
  let token = ''
  try {
    token = new URL(req.url, 'http://localhost').searchParams.get('token') ?? ''
  } catch {
    // URL invalid akan ditolak sebagai token kosong.
  }
  if (!safeEqual(token, TOKEN)) {
    done(false, 401, 'Token tidak valid')
    return
  }
  done(true)
}

function send(socket, payload) {
  if (socket.readyState === socket.OPEN) socket.send(JSON.stringify(payload))
}

function cleanText(value, maxLength) {
  if (typeof value !== 'string') return ''
  return value.trim().slice(0, maxLength)
}

function parseRun(message) {
  const prompt = cleanText(message.prompt, MAX_PROMPT_LENGTH + 1)
  if (!prompt) throw new Error('Prompt kosong')
  if (prompt.length > MAX_PROMPT_LENGTH) throw new Error(`Prompt melebihi batas ${MAX_PROMPT_LENGTH} karakter`)

  const providerId = cleanText(message.providerId || 'claude-cli', 100)
  const provider = getProvider(providerId)
  if (!provider) throw new Error(`Provider tidak tersedia: ${providerId}`)

  const sessionId = cleanText(message.sessionId, 100) || randomUUID()
  if (!UUID_PATTERN.test(sessionId)) throw new Error('sessionId bukan UUID valid')

  const agent = message.agent && typeof message.agent === 'object' ? message.agent : {}
  const agentId = cleanText(agent.id || 'personal-assistant', 100)
  if (!SAFE_ID_PATTERN.test(agentId)) throw new Error('agent.id tidak valid')
  const model = cleanText(agent.model, 100)
  if (model && !SAFE_ID_PATTERN.test(model)) throw new Error('Model tidak valid')
  const systemPrompt = cleanText(agent.systemPrompt, MAX_SYSTEM_PROMPT_LENGTH + 1)
  if (systemPrompt.length > MAX_SYSTEM_PROMPT_LENGTH) {
    throw new Error(`System prompt melebihi batas ${MAX_SYSTEM_PROMPT_LENGTH} karakter`)
  }
  const toolPolicy = TOOL_POLICIES.has(agent.toolPolicy) ? agent.toolPolicy : 'standard'

  return {
    provider,
    request: {
      prompt,
      sessionId,
      resume: message.resume === true,
      model,
      systemPrompt,
      toolPolicy,
      agentId,
    },
  }
}

const wss = new WebSocketServer({ host: HOST, port: PORT, verifyClient })

wss.on('connection', (socket) => {
  if (wss.clients.size > MAX_CLIENTS) {
    send(socket, { type: 'error', text: `Gateway penuh (maks ${MAX_CLIENTS} koneksi)` })
    socket.close()
    return
  }

  let activeRun = null
  let outputBytes = 0
  send(socket, { type: 'hello', protocolVersion: 1, providers: listProviders() })

  socket.on('message', (raw) => {
    let message
    try {
      message = JSON.parse(raw.toString())
    } catch {
      send(socket, { type: 'error', text: 'Pesan bukan JSON valid' })
      return
    }

    if (message?.type === 'cancel') {
      if (activeRun) activeRun.cancel()
      else send(socket, { type: 'error', text: 'Tidak ada run yang aktif' })
      return
    }
    if (message?.type !== 'run') {
      send(socket, { type: 'error', text: `Tipe pesan tidak didukung: ${message?.type ?? 'unknown'}` })
      return
    }
    if (activeRun) {
      send(socket, { type: 'error', text: 'Masih ada run yang aktif' })
      return
    }

    let parsed
    try {
      parsed = parseRun(message)
    } catch (error) {
      send(socket, { type: 'error', text: error.message })
      return
    }

    outputBytes = 0
    const { provider, request } = parsed
    send(socket, {
      type: 'session',
      sessionId: request.sessionId,
      providerId: provider.id,
      agentId: request.agentId,
    })

    try {
      activeRun = provider.start(request, {
        onChunk(text, level) {
          outputBytes += Buffer.byteLength(text, 'utf8')
          if (outputBytes > MAX_OUTPUT_BYTES) {
            send(socket, { type: 'error', text: `Output melebihi batas ${MAX_OUTPUT_BYTES} byte` })
            activeRun?.dispose()
            activeRun = null
            return
          }
          send(socket, { type: 'chunk', text, level })
        },
        onDone(result) {
          send(socket, { type: 'done', providerId: provider.id, ...result })
          activeRun = null
        },
        onError(text) {
          send(socket, { type: 'error', text })
          activeRun = null
        },
      })
    } catch (error) {
      activeRun = null
      send(socket, { type: 'error', text: `Provider gagal dimulai: ${error.message}` })
    }
  })

  socket.on('close', () => {
    activeRun?.dispose()
    activeRun = null
  })
  socket.on('error', () => {
    activeRun?.dispose()
    activeRun = null
  })
})

console.log(`[gateway] listening on ws://${HOST}:${PORT}`)
console.log(`[gateway] providers: ${listProviders().map((provider) => provider.id).join(', ')}`)
console.log(`[gateway] origin allowlist: ${[...ALLOWED_ORIGINS].join(', ')}`)
if (TOKEN_AUTOGENERATED) {
  console.log(`[gateway] token (auto): ${TOKEN}`)
  console.log(`[gateway] set GATEWAY_TOKEN dan VITE_GATEWAY_WS_TOKEN agar token stabil`)
} else {
  console.log('[gateway] token: dari environment')
}
